name: 'ftp-upload-action'
author: 'Tim Bernhard <ftp-action@genieblog.ch>'
description: 'Automate copying your files via FTP using this GitHub action.'
inputs:
  host:
    description: 'FTP host'
    required: true
  user:
    description: 'FTP user'
    required: true
  password:
    description: 'FTP password'
    required: true
  forceSsl:
    description: 'Force SSL encryption'
    required: false
    default: 'false'
  localDir:
    description: 'Local directory'
    required: true
    default: '.'
  remoteDir:
    description: 'Remote directory'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'blue'
  icon: 'upload-cloud'
